services:
  database:
    container_name: database
    image: postgres:16.4
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      depends_on:
        - database
      ports:
        - "${PGADMIN_PORT}:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      restart: always

volumes:
  db-data: